name: Greet and Guide for Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  issue_greet_label_assign:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Ensure 'gssoc2025' label exists
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = 'gssoc2025';
            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const exists = labels.data.some(label => label.name === labelName);
            if (!exists) {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: labelName,
                color: '0e8a16', // green
                description: 'GSSoC 2025 contribution'
              });
            }

      - name: Add 'gssoc2025' label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: gssoc2025

      - name: Assign issue opener
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.issue.user.login }}

      - name: Greet and post guidelines for Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const guidelines = `
            👋 Hi @${{ github.event.issue.user.login }}! Thanks for opening this issue.

            **Contributor Guidelines**
            1. Make sure your issue is clear and descriptive.
            2. If reporting a bug, include steps to reproduce it.
            3. If suggesting a feature, explain why it’s useful.
            4. Be respectful and constructive.
            5. Read our [Contributing Guide](https://github.com/opensource-society/notesvault/blob/main/CONTRIBUTING.md)

            Good luck contributing to NotesVault! 🚀
            `;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: guidelines
            });

  pr_greet_guidelines:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Greet and post guidelines for PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const guidelines = `
            👋 Hi @${{ github.event.pull_request.user.login }}! Thanks for your pull request.

            **Contributor Guidelines**
            1. Link to related issues if any.
            2. Follow the code style and test requirements.
            3. Be respectful and constructive.
            4. Read our [Contributing Guide](https://github.com/opensource-society/notesvault/blob/main/CONTRIBUTING.md)

            All the best! 🚀
            `;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: guidelines
            });
